// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace VocationPlugin {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("VocationPlugin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string INFO_SAVING {
            get {
                return ResourceManager.GetString("INFO_SAVING", resourceCulture);
            }
        }
        
        internal static string ERR_NOT_LOGGED_IN {
            get {
                return ResourceManager.GetString("ERR_NOT_LOGGED_IN", resourceCulture);
            }
        }
        
        internal static string ERR_SAVING {
            get {
                return ResourceManager.GetString("ERR_SAVING", resourceCulture);
            }
        }
        
        internal static string ERR_NOT_CONSOLE_COMMAND {
            get {
                return ResourceManager.GetString("ERR_NOT_CONSOLE_COMMAND", resourceCulture);
            }
        }
        
        internal static string ERR_UNKNOWN_VOCATION {
            get {
                return ResourceManager.GetString("ERR_UNKNOWN_VOCATION", resourceCulture);
            }
        }
        
        internal static string ERR_SAME_VOCATION {
            get {
                return ResourceManager.GetString("ERR_SAME_VOCATION", resourceCulture);
            }
        }
        
        internal static string INFO_LEVELUP_ATTACK {
            get {
                return ResourceManager.GetString("INFO_LEVELUP_ATTACK", resourceCulture);
            }
        }
        
        internal static string INFO_STAT_LEVEL {
            get {
                return ResourceManager.GetString("INFO_STAT_LEVEL", resourceCulture);
            }
        }
        
        internal static string INFO_STAT_ATTACK {
            get {
                return ResourceManager.GetString("INFO_STAT_ATTACK", resourceCulture);
            }
        }
        
        internal static string HELP_CMD_CHANGEVOCATION {
            get {
                return ResourceManager.GetString("HELP_CMD_CHANGEVOCATION", resourceCulture);
            }
        }
        
        internal static string INFO_VOCATION_CHANGED {
            get {
                return ResourceManager.GetString("INFO_VOCATION_CHANGED", resourceCulture);
            }
        }
        
        internal static string INFO_LEVELUP {
            get {
                return ResourceManager.GetString("INFO_LEVELUP", resourceCulture);
            }
        }
        
        internal static string USAGE_CHANGE_VOCATION {
            get {
                return ResourceManager.GetString("USAGE_CHANGE_VOCATION", resourceCulture);
            }
        }
        
        internal static string HELP_CMD_STATS {
            get {
                return ResourceManager.GetString("HELP_CMD_STATS", resourceCulture);
            }
        }
        
        internal static string ERR_NO_VOCATION {
            get {
                return ResourceManager.GetString("ERR_NO_VOCATION", resourceCulture);
            }
        }
    }
}
